import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../../../components/header";
import Footer from "../../../../components/footer";
import RelatedViewCollection from "../../../../components/home/relatedViewCollection";
import { useEffect, useState } from "react";
import Customize from "../../../../components/customize/Customize";

const inter = Inter({ subsets: ["latin"] });

const Page = () => {
  let [imgDataArr, setImgDataArr] = useState([]);

  useEffect(() => {
    let data = [
      {
        name_: "Classic Mafia Long Sleave",
        price_: "$48.98",
        colors_: "white, black, yellow, gray, pink, beige, gold, purple, blue",
        sizes_: ["S", "X", " L"],
        color1_: "#eff1b7",
        color2_: "#9cf1ff",
        color3_: "#cfcfcf",
        dtImgArr: [
          { src: "/img/customize/ClassicMafiaLongSleave/1.jpg" },
          { src: "/img/customize/ClassicMafiaLongSleave/2.jpg" },
          { src: "/img/customize/ClassicMafiaLongSleave/3.jpg" },
          { src: "/img/customize/ClassicMafiaLongSleave/4.jpg" },
        ],
      },
    ];
    setImgDataArr(data);
  }, []);

  return (
    <>
      <Head>
        <title>stay gold studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        {imgDataArr &&
          imgDataArr.map((itm, i) => <Customize itm={itm} key={i} />)}
        <RelatedViewCollection />
        <Footer />
      </main>
    </>
  );
};

export default Page;
