import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/header";
import Footer from "../../components/footer";
import ViewCollection from "../../components/home/Viewcollection";
import StickyCollection from "../../components/home/stickyCollection";
import RelatedViewCollection from "../../components/home/relatedViewCollection";
import AfterHeader from "../../components/home/afterHeader";
import SliderSection from "../../components/home/sliderSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>stay gold studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <AfterHeader />
        <ViewCollection />
        <StickyCollection />
        <RelatedViewCollection />
        <SliderSection />
        <Footer />
      </main>
    </>
  );
}
