import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/header";
import Footer from "../../components/footer";
import CookieFooter from "../../components/cookiefooter";
import ViewCollection from "../../components/home/viewcollection";
import StickyCollection from "../../components/home/stickycollection";
import RelatedViewCollection from "../../components/home/relatedviewcollection";
import AfterHeader from "../../components/home/afterheader";
import SliderSection from "../../components/home/slidersection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>owl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />

        <AfterHeader />
        <ViewCollection />
        <StickyCollection />
        <RelatedViewCollection />
        <SliderSection />
        <Footer />
        <CookieFooter />
      </main>
    </>
  );
}
